name: Build SSL Checker
on:
  push:
    branches: 
      - master
  schedule:
      - cron: '0 16 * * *'
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Node Packages and Downloading Scripts
        run: |
          npm i
          wget https://cdn.jsdelivr.net/gh/lbr77/CheckSSL@master/checker.sh -O ./checker.sh
          wget https://cdn.jsdelivr.net/gh/lbr77/CheckSSL@master/runcheck.sh -O ./runcheck.sh
          chmod +x checker.sh
      - name: Build
        run: |
          npm run build
          ./checker.sh $SERVERS
          echo $DOMAIN > ./public/CNAME
        env:
          SERVERS: ${{secrets.SERVERS}}
          DOMAIN: ${{secrets.DOMAIN}}
      - name: Commit Changes
        run: |
          cd ./public
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update SSL status via Github Actions"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: public
